name: cybo
channels:
  - defaults
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cryptography=43.0.3
  - frozenlist=1.5.0
  - google-api-core=2.19.1
  - google-api-python-client=2.154.0
  - google-auth=2.29.0
  - google-auth-httplib2=0.2.0
  - googleapis-common-protos=1.63.2
  - httplib2=0.22.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - libabseil=20240116.2
  - libffi=3.4.4
  - libprotobuf=4.25.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - oauth2client=4.1.3
  - openssl=3.0.15
  - pandas=2.2.3
  - pip=24.2
  - propcache=0.2.0
  - proto-plus=1.24.0
  - protobuf=4.25.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.21
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pypdf=4.2.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - requests=2.32.3
  - rsa=4.7.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - uritemplate=4.1.1
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yarl=1.18.0
  - zlib=1.2.13
